package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.application.Application;
import javafx.event.ActionEvent;

public class HomeController {
	@FXML
	private Button PractiseButton;
	
	private Main _main;

	// Event Listener on Button[#PracticeButton].onAction
	@FXML
	public void practiseButtonClicked(ActionEvent event) {
		// TODO Autogenerated
		_main.showPractiseScene();
	}
	
	public void setParent(Main main) {
		_main = main;
	}
}
