package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class LoginSceneController {
	@FXML
	private TextField textFieldForUsername;
	@FXML
	private Button startBtn;
	
	private Main _main;

	public void setParent(Main main) {
		_main = main;
	}
	
	// Event Listener on Button[#startBtn].onAction
	@FXML
	public void start(ActionEvent event) {
		// TODO Autogenerated
	}
}
