package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class ModeSettingSceneController {
	@FXML
	private Button normalBtn;
	@FXML
	private Button endlessBtn;
	
	private Main _main;

	public void setParent(Main main) {
		_main = main;
	}

	// Event Listener on Button[#normalBtn].onAction
	@FXML
	public void goNormal(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#endlessBtn].onAction
	@FXML
	public void goEndless(ActionEvent event) {
		// TODO Autogenerated
	}
}
