package application;

import javafx.fxml.FXML;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;

import com.jfoenix.controls.JFXListView;

public class PickQuestionListSceneController {
	@FXML
	private JFXListView _allQuestionsList;
	@FXML
	private JFXButton _addBtn;
	@FXML
	private JFXButton _deleteBtn;
	@FXML
	private JFXListView _userChoseList;
	@FXML
	private JFXButton _confirmBtn;

	// Event Listener on JFXButton[#_addBtn].onAction
	@FXML
	public void addBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#_deleteBtn].onAction
	@FXML
	public void deleteBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#_confirmBtn].onAction
	@FXML
	public void confirmBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
