package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ProgressIndicator;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class QuestionSceneController {
	@FXML
	private Button _previousBtn;
	@FXML
	private Label _question;
	@FXML
	private Button _nextBtn;
	@FXML
	private ProgressIndicator _progressInd;
	@FXML
	private Button _recordBtn;
	@FXML
	private Button _finishBtn;
	@FXML
	private Button _helpBtn;

	// Event Listener on Button[#_previousBtn].onAction
	@FXML
	public void previousBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#_nextBtn].onAction
	@FXML
	public void nextBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#_recordBtn].onAction
	@FXML
	public void recordBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#_finishBtn].onAction
	@FXML
	public void finishBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#_helpBtn].onAction
	@FXML
	public void helpBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
