package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;
import javafx.stage.Stage;

public class QuestionSetEditPanelController {
	@FXML
	private ListView listOfQuestions;
	@FXML
	private Button addQuestionBtn;
	@FXML
	private Button delteQuestionBtn;
	@FXML
	private Button confirmBtn;
	
	private Stage _editPanelStage;
	
	public void initData(Stage stage) {
		_editPanelStage = stage;
	}

	// Event Listener on Button[#addQuestionBtn].onAction
	@FXML
	public void addNewQuestion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#delteQuestionBtn].onAction
	@FXML
	public void delteQuestion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#confirmBtn].onAction
	@FXML
	public void confirmAndExit(ActionEvent event) {
		_editPanelStage.close();
	}
}
