package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class ResultSceneController implements Initializable {
	@FXML
	private Label _correctness;
	@FXML
	private Label _answerLabel;
	@FXML
	private Button _replayBtn;
	@FXML
	private Button _retryBtn;
	@FXML
	private Button _nextBtn;
	@FXML
	private Button _finishBtn;
	@FXML
	private Button _helpBtn;
	private FoundationBoardController _parentController;

	// Event Listener on Button[#_replayBtn].onAction
	@FXML
	public void replayBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#_retryBtn].onAction
	@FXML
	public void retryBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#_nextBtn].onAction
	@FXML
	public void nextBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#_finishBtn].onAction
	@FXML
	public void finishBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#_helpBtn].onAction
	@FXML
	public void helpBtnClicked(ActionEvent event) {
		// TODO Autogenerated
	}

	public void setParent(FoundationBoardController controller) {
		// TODO Auto-generated method stub
		_parentController = controller;
	}

	/**
	 * Tell controller the correctness of the answer.
	 * 
	 * @param isCorrect
	 */
	public void resultIsCorrect(boolean isCorrect) {
		// TODO Auto-generated method stub
		if (!isCorrect) {
			// TODO if can retry
			if (_parentController.canRetry()) {
				_retryBtn.setVisible(true);
			} else {
				_retryBtn.setVisible(false);
			}
			_correctness.setText("Wrong");
		} else {
			_retryBtn.setVisible(false);
			_correctness.setText("Correct");
		}
	}

	/**
	 * Tell controller what the user said
	 * 
	 * @param userAnswer
	 */
	public void setUserAnswer(String userAnswer) {
		_answerLabel.setText(userAnswer);
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub

	}
}
