package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.TextInputDialog;
import javafx.stage.Stage;

import java.net.URL;
import java.util.Optional;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class SettingsController implements Initializable{
	@FXML
	private ComboBox quesitonSetComboBox;
	@FXML
	private Button editQuestionSetBtn;
	@FXML
	private Button addNewSetBtn;
	@FXML
	private Button deleteSetBtn;
	@FXML
	private Label questionListLabel;
	@FXML
	private TextField numOfQuestionsTxetFieldForRandom;
	@FXML
	private Button pickARandomListBtn;
	@FXML
	private Button pickYourselfBtn;
	@FXML
	private Button confirmBtn;
	
	private Stage _editPanelStage;
	private Main _main;
	private QuestionModel _questionModel; 

	public void setParent(Main main) {
		_main = main;
		_questionModel = QuestionModel.getInstance();
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
	
	// Event Listener on Button[#addNewSetBtn].onAction
	@FXML
	public void addNewSet(ActionEvent event) {
		TextInputDialog dialog = new TextInputDialog();
		dialog.setTitle("Text Input Dialog");
		dialog.setHeaderText("Look, a Text Input Dialog");
		dialog.setContentText("Please enter your name:");
		
		Optional<String> result = dialog.showAndWait();
		if (result.isPresent()){
			_questionModel.createLocalQuestionSet(result.get());
			openeditPanel(result.get());
		}
	}
	// Event Listener on Button[#deleteSetBtn].onAction
	@FXML
	public void deleteSet(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#pickARandomListBtn].onAction
	@FXML
	public void pickRandomList(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#pickYourselfBtn].onAction
	@FXML
	public void pickCustomizedList(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#confirmBtn].onAction
	@FXML
	public void confirmSetting(ActionEvent event) {
		_main.showHome();
	}
	public void openeditPanel(String name){
		//TODO pass questionSetName to edit panel
		if (_editPanelStage != null) {
			_editPanelStage.show();
			_editPanelStage.toFront();
		}else {
			_editPanelStage = new Stage();
			Scene editPanelScene = _main.loadScene("QuestionSetEditPanel.fxml");
			QuestionSetEditPanelController editPanelController = (QuestionSetEditPanelController)editPanelScene.getUserData();
			editPanelController.initData(_editPanelStage);
			_main.showScene(_editPanelStage, editPanelScene);
		}
	}
}
